### ISSUE TITLE
Docker - Invalid characters for a local volume name

### ISSUE THREAD

**Issue by GabrielKlugSecurrency** [DataDog/KubeHound#251]
**Describe the bug**
When downloading the binary (v1.4.0) and trying to run it with `./kubehound` we got the following errors:

```bash
FATA[15:10:04] error starting the kubehound stack: Error response from daemon: create datadog/openmetrics.yaml: "datadog/openmetrics.yaml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. Please make sure your Docker is correctly installed and that you have enough disk space available.  
```

```bash
FATA[15:10:08] error starting the kubehound stack: Error response from daemon: create datadog/datadog.yaml: "datadog/datadog.yaml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. Please make sure your Docker is correctly installed and that you have enough disk space available.  
```

**To Reproduce**
1. Download the binary v1.4.0
2. Have Docker v27.x.x and docker compose 2.29
3. `chmod +x .kubehound`
4. `./kubehound`
5. See error

**Expected behavior**
Kubehound run without issues

**Desktop (please complete the following information):**
 - OS: MacOS M1
 - Kubehound Version: v1.4.0
 - Docker version: version 27.1.1, build 6312585
 - Docker compose version: 2.29.1-desktop.1

**Additional context**
With docker 23.0.5 it seems to work properly.

**Comment by jt-dd** [comment]
Hello @GabrielKlugSecurrency,

Thank for reporting the issue. The crash is being caused because I think you have `DD_API_KEY` and `DD_APP_KEY` en var setup. We are pushing a fix and should roll-out a new version tomorrow. 
As a temp fix. you can unset the 2 env vars, and `kubehound` should be running fine on your laptop.

Also I see you are running on mac, you can use `brew install kubehound` and `brew update && brew upgrade kubehound`.

**Comment by GabrielKlugSecurrency** [comment]
Hi @jt-dd, you were right. Unsetting the env vars solved the error. 
Thanks for it!
